### ISSUE TITLE
Signin URI does not work for Chromium on KDE

### ISSUE THREAD

**Issue by mzabaluev** [flathub/com.slack.Slack#56] opened 2019-08-28 09:44 UTC
With revision 45cd270cb3a69dc2c9c08cd9211068336fdc52ece08c77e5413a44f70e2a0d5b, I see the same symptoms as in #41: after signing in with the browser, the magic login link opens the Slack app window, but it only shows the Sign In view.

**Comment by mzabaluev** [comment] 2019-08-28 10:07
Content of the desktop entry in `/var/lib/flatpak/exports/share/applications/com.slack.Slack.desktop`:

```
[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=slack --file-forwarding com.slack.Slack @@u %U @@
Icon=com.slack.Slack
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;
X-Desktop-File-Install-Version=0.23
StartupWMClass=Slack
X-Flatpak-RenamedFrom=slack.desktop;
X-Flatpak=com.slack.Slack
```

**Comment by FakeShemp** [comment] 2020-03-25 21:37
I personally can not get xdg-links to work with Snap packages (like Ubuntu's Chromium). This will cause an issue with these URIs.

**Comment by japrogramer** [comment] 2020-10-08 04:45
I have this issue, maybe.

installed slack in --user but the first link to 'Sign in to Slack' is a green button
and when click nothing happens.

**Comment by ADawesomeguy** [comment] 2020-10-21 05:56
I am using Arch Linux with KDE Plasma, and I had the same issue. What fixed it for me was installing xdg-desktop-portal (not the kde one). Hope this helps!

This also fixed other URLs not working in Slack.

**Comment by mmatrosov** [comment] 2020-12-09 11:55
Same issue on Ubuntu 20.04. No workaround yet :(

**Comment by cho2** [comment] 2020-12-15 01:58
It works on me (openSUSE Tumbleweed, Flatpak 1.8.3, Slack 4.12.0) with sign in from Firefox

**Comment by thegarlynch** [comment] 2021-12-02 01:45
edit .config/mimeapps.list
to include : 
x-scheme-handler/slack=com.slack.Slack.desktop

and then restart or logout

**Comment by zarelit** [comment] 2022-02-24 11:09
Is this the same of #160 ?

**Comment by cgoetzke** [comment] 2022-04-11 21:23
> edit .config/mimeapps.list to include : x-scheme-handler/slack=com.slack.Slack.desktop
> 
> and then restart or logout
> 
> https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list

I was having this problem with Vivaldi (Chromium-based).

As a workaround, using Firefox to login & xdg-open com.slack.Slack worked.

As a solution, adding the above entry to `.config/mimeapps.list` made it work from Vivaldi.

Arch Wiki, once again, to the rescue (even though I'm on Fedora).

**Comment by kanwarplaha** [comment] 2022-04-27 06:43
I have the following in `$HOME/.config/mimeapps.list`:
`x-scheme-handler/slack=slack.desktop`

However, it does not work.

Distribution: openSUSE Tumbleweed

**Comment by awerlang** [comment] 2022-05-06 01:16
Workaround:
1) Downgrade to oldest suported Slack version

`flatpak update --commit=5ae2f31e0a632f0b0114d25d6752758864f4f8480a52d6036acf8066b26b8d25 com.slack.Slack`

2) Login to the app

3) Update to latest Slack

`flatpak update`

**Comment by dottorblaster** [comment] 2022-05-28 11:17
Plus one. Don't know what to do.

**Comment by stefanobartoletti** [comment] 2022-06-01 08:20
@dottorblaster The workaround suggested by @awerlang works for me, I'm on OpenSUSE Tumbleweed.

It is a bit clunky, but usually you have to join a new workspace only from time to time, so until they fix it, it can be a solution.

**Comment by dottorblaster** [comment] 2022-06-01 08:33
@stefanobartoletti thanks for the answer! Sadly, due to security reasons one of my organizations logs me out every week, so I guess it's not feasible for me :sweat:

**Comment by kanwarplaha** [comment] 2022-07-13 06:18
Same here. Every now and then, Slack asks me to sign-in again. The sign-in
always fails with Chrome. I have to install Firefox just to sign-in to
Slack. What a terrible login design, given that Slack itself is basically a
browser window wrapped up as a desktop application.

**Comment by WarheadsSE** [comment] 2022-09-20 18:37
I am experiencing this. Reset my SSO, and thus need to re-login. I can see that the application receives the call from `xdg-open`, but there is no apparent action taken:

```
[09/20/22, 14:32:08:275] info: Store: HANDLE_DEEP_LINK {
  "url": "slack://tBOGUS/magic-login/REDACTED"
}
```

**Comment by TwidgeVR** [comment] 2022-10-04 19:25
For anyone who gets here searching for Slack not signing in on KDE with Chrome or Chromium based browsers, this is the crux:

https://bugs.kde.org/show_bug.cgi?id=451018

In summary:

> Chrome calls xdg-open, which calls kde-open5, which uses KIO::OpenUrlJob internally. That uses QUrl everywhere to parse and store urls. The problem is that QUrl internally sanitizes the hostname part of the url (anything between the slack:// and the next /) and thereby converts it to lowercase

I'm guessing the issue is similar for other WMs if they happen to be using Qt and QUrl for this purpose.  The ticket is marked 'resolved by upstream' as lowercasing the URL is correct RFC behavior and "likely" an intentional choice by QUrl developers.  The 'fix' is to wait for Slack to make their comparison case insensitive...

A quick fix for the impatient of us in the dust who need to sign in _right now_, is to watch the process list for the passing of the magic URL, copy it with the correct case, and open slack using it as an argument:

```
#  while sleep .1; do ps aux | grep slack | grep -v grep | grep magic; done
-----
bogusr       2110  0.0  0.2 268980 39224 ?        Sl   14:45   0:00 kde-open5 slack://T5NDEADBEEF/magic-login/1234573490663-fdf3cf84ac5e13f40497ec690b3f1fc8e96ed86da0b3a2535f186a030d5ec809

# /usr/lib/slack/slack --enable-crashpad slack://T5NDEADBEEF/magic-login/1234573490663-fdf3cf84ac5e13f40497ec690b3f1fc8e96ed86da0b3a2535f186a030d5ec809
```

**Comment by restena-sw** [comment] 2023-02-17 07:47
The much easier way to get the URL is to open Chromium's Developer Tools - the URL will be right there after the log entry "launched external handler for ..."

**Comment by mahtjarohst** [comment] 2023-03-02 18:08
> The much easier way to get the URL is to open Chromium's Developer Tools - the URL will be right there after the log entry "launched external handler for ..."

Once you've found this URL what do you do with it to make it open in slack?

**Comment by restena-sw** [comment] 2023-03-03 07:37
Quit Slack, and re-launch on the command-line with this URL as the first and only parameter.

**Comment by kanwarplaha** [comment] 2023-03-12 11:59
You can also just copy the URL and click on the Slack window that says "Log In ...". It works for me.

**Comment by RichardsonWTR** [comment] 2023-04-04 11:53
I had this issue with Chrome and I logged in by using Firefox

Slack version: 8f777cfcdeadd6ddb12b43760cd003c71c35d0c9@1680598645 Snap 4.29.149 64-bit

**Comment by gunzy83** [comment] 2023-04-13 23:04
I just started using the Flatpak and ran into this issue. I was already aware of the issue with KDE and had my own [workaround script](https://github.com/gunzy83/dotfiles/blob/master/dot_bin/executable_slack_login_capture) that I run when signing into any workspaces (I have a few to login to). I have updated for the flatpak (removing the executable and `-s` from the command and replacing it with `flatpak run com.slack.Slack`. I did notice that it tries to run the login command with `/app/extra/lib/slack/slack` which does not exist, indicates that the Flatpak version is not registered in XDG correctly?

I may switch to a solution like the one in this [comment](https://bugs.kde.org/show_bug.cgi?id=451018#c3) though this will still not work with the Flatpak as it stands.

**Comment by timtait** [comment] 2023-04-19 09:25
Just had this same issue on openSUSE Tumbleweed when trying to sign in to Slack workspaces via Firefox. 

I tried a different browser and randomly grabbed the ungoogled-chromium flatpak, now everything works as expected.

**Comment by jacohend** [comment] 2023-06-13 22:23
No URI works besides firefox, it seems, for sign-in or even external links. I'm on arch using brave. Slack opens no links when $BROWSER set to brave in /etc/environment

**Comment by raulillo82** [comment] 2023-09-12 10:02
> Workaround:
> 
>     1. Downgrade to oldest suported Slack version
> 
> 
> `flatpak update --commit=5ae2f31e0a632f0b0114d25d6752758864f4f8480a52d6036acf8066b26b8d25 com.slack.Slack`
> 
>     2. Login to the app
> 
>     3. Update to latest Slack
> 
> 
> `flatpak update`

This commit does not seem to exist any more. Same for 8f777cfcdeadd6ddb12b43760cd003c71c35d0c9@1680598645  in one of the latest comments. Any other workaround?

**Comment by sombriks** [comment] 2023-10-10 13:42
Hello, i can confirm this is a google-chrome related bug, i just used firefox instead to login and join the workspace

**Comment by golgor** [comment] 2023-11-30 08:39
> **Try firefox**, had same issue with google chrome.

Helped me out, thanks for the tip! I really like Vivaldi with all of its features and cool stuff that no other browser has, but I just feel that there are some basic stuff that just doesn't work anymore... This is not the first case.

**Comment by m-czernek** [comment] 2023-12-13 09:05
I'm having the same problem with Firefox - see https://github.com/flathub/com.slack.Slack/issues/230. I stopped using the Slack flatpak because I still can't get it to log in.

**Comment by evan-a-a** [comment] 2023-12-15 21:23
I'm not able to reproduce this on Fedora 39 Gnome, Chrome 120 (flatpak) and latest Slack. From reading the history of this, it seems the bug is specific to KDE, is that correct?

**Comment by awerlang** [comment] 2023-12-17 03:55
This MUST be addressed by any of:
- Slack app
- kde-open5
- Qt's QUrl

https://bugs.kde.org/show_bug.cgi?id=451018#c7

Slack packaged as flatpak can not solve the issue besides sharing workarounds.

**Comment by m-czernek** [comment] 2023-12-18 08:36
Just thinking out loud here, with the RPM version of slack, KDE users use an xdg-open wrapper as a workaround:

```
    #!/bin/bash

    # Wrapper for xdg-open which fixes auth for Slack URLs
    #
    if [[ "${1:-}" =~ ^slack:// ]]; then
      exec /usr/lib/slack/slack "$@";
    fi
    exec /usr/bin/xdg-open "$@";
```

I haven't done any flatpak packaging, but would it be possible maybe to include something like this in the flatpak internally?

**Comment by ZVNexus** [comment] 2024-01-15 16:10
As a note, I am not able to reproduce this in KDE Plasma 6, which releases next month. Close?

**Comment by kanwarplaha** [comment] 2024-02-04 00:44
@ZVNexus I can. There is, in fact, no way to sign in under Plasma 6. I tried changing browser to Chrome and Firefox. The request goes to the browser from Slack but never gets a callback to Slack.

**Comment by ZVNexus** [comment] 2024-02-04 13:08
> @ZVNexus I can. There is, in fact, no way to sign in under Plasma 6. I tried changing browser to Chrome and Firefox. The request goes to the browser from Slack but never gets a callback to Slack.

Will retest under RC2 but was working as of RC1.

**Comment by ZVNexus** [comment] 2024-02-04 14:10
@kanwarplaha  I just did a fresh installation of Fedora 40 (KDE 6 RC2) and I am able to join a workspace using Firefox.

I switched to Chromium to try there and that doesn't work. Only Firefox works.

**Comment by ajossorioarana** [comment] 2024-03-12 14:19
Couldn't log in, using Firefox on openSUSE with KDE Plasma 5, neither with flatpak nor rpm.

Finally what did the trick was this ([original source](https://www.reddit.com/r/Kubuntu/comments/x3gurd/comment/jagmveg/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button))

> A workaround Slack is providing from a support case:
> 
> open the Workspace Url with the "login fallback" option:
> https://<yourslackworkspace>.slack.com/ssb/signin_redirect/fallback
> 
> click on "Copy Sign-In Key" and switch back to the slack application which then will complete the login.

**Comment by mrjoe7** [comment] 2024-09-19 20:20
For me update to 4.39.95 fixed the issue (openSUSE Tumbleweed, KDE Plasma 6.1.5)

**Comment by ZVNexus** [comment] 2024-09-19 23:23
Closing as per above, reopen if still an issue.

**Closed by ZVNexus** 2024-09-19 23:23 UTC
Labels: upstream bug

**Comment by DavidNemeskey** [comment] 2025-01-16 09:47
Hi all, I just had the same issue in KDE Neon 6.2, (Slack: 4.41.105, Firefox: 134.0.1). Neither the flatpak, nor the official version worked with Firefox. I had to resort to using Chromium.

**Comment by art-solopov** [comment] 2025-02-25 11:26
I also had this issue on Firefox, but the [workaround](https://github.com/flathub/com.slack.Slack/issues/56#issuecomment-525676488) helped.
