### ISSUE TITLE
Signin redirect does not work

### ISSUE THREAD

**Issue by sdahdah** [flathub/com.slack.Slack#41] opened 2019-06-03 15:44 UTC
**Problem:**
Cannot sign in to Slack because the browser sign-in redirect does not work.

**Steps to Reproduce:**
1. Install com.slack.Slack from Flathub
2. Launch application and click "Sign In"
3. Sign in through web browser
4. Click "Open with xdg-open" when prompted by browser
5. Slack app opens, but the screen is still stuck on the original "Sign In" screen
6. I can click "Sign In" again, and it re-opens the browser etc...

**Workaround:**
Downgrade to commit `810ae703189dd439c5a7059accf33af495d415e2d46545a3bfcccf445ab7c092`

**System:**
OS: Arch Linux x86_64 
Host: 20FDCTO1WW ThinkPad Yoga 260 
Kernel: 5.1.6-arch1-1-ARCH 
DE: Xfce 
WM: Xfwm4 
Browser: Chrome or Firefox (same problem)

**Comment by FakeShemp** [comment] 2019-06-03 16:19
Seems the regression is in commit `892db0196ca1971b772f37df2bf4dad021e5579486454069808be7fabdbdd393` but I don't know what it is yet.

**Comment by FakeShemp** [comment] 2019-06-03 18:08
Should be fixed in newest commit.

**Closed by FakeShemp** 2019-06-03 18:08 UTC

**Comment by sdahdah** [comment] 2019-06-07 14:59
Thanks for fixing this so quickly! It works perfectly now

**Comment by AmineKh14** [comment] 2022-01-01 15:09
It still now working for me

**Comment by syerad** [comment] 2022-02-07 14:55
Seems that the problem is there again.
For me it's currently not possible adding a workspace to the slack App. It only works in Browsers

**Comment by WhyNotHugo** [comment] 2022-02-08 13:47
@[AmineKh14](https://github.com/AmineKh14) @[syerad](https://github.com/syerad)

Works for me. What version do you have installed? What browser? What exactly doesn't work?

**Comment by syerad** [comment] 2022-02-17 16:08
> @[AmineKh14](https://github.com/AmineKh14) @[syerad](https://github.com/syerad)
> 
> Works for me. What version do you have installed? What browser? What exactly doesn't work?

Same as @DoppleDankster mentioned.
I've tried all available builds (AUR,Flatpak and Snap).
With Chrome it is not working but I found out that in Firefox it is working...

**Comment by YoavNordmann** [comment] 2022-03-08 06:42
I am having the same problem.
Any solutions yet ?

**Comment by ethouris** [comment] 2022-04-19 09:55
It still doesn't work. I have presently the newest version that `snap` can retrieve. I am signed in in the browser (Brave, Chrome clone) and viewing the slack workspace there, and when I select the "Open the Slack App", the Slack app opens through xdg-open, and... requests me to sign in. If I click this button, it redirects me to the browser where I am already signed in, so it asks me to open the Slack app ... and so round-robin.

**Comment by FakeShemp** [comment] 2022-04-19 10:01
@ethouris 
This is not for the snap version.

**Comment by FakeShemp** [comment] 2022-04-19 10:08
Is anyone experiencing this on *only* the flatpak version. If not, I will close this as an upstream issue.

**Comment by Saijin-Naib** [comment] 2022-04-27 04:17
Currently experiencing this on the flatpak version only, yes.

**Comment by YoavNordmann** [comment] 2022-06-12 09:22
I am experiencing this on the flatpak version. 
Using Firefox works, but Brave doesn't.

**Comment by bryankaplan** [comment] 2022-07-24 21:32
I am experiencing this issue too. Looks like a regression.
