### ISSUE TITLE
Random Freezes, How to find the issue?

### ISSUE THREAD

**Issue by gmaratos** [flathub/com.slack.Slack#109] opened 2021-01-23 05:25 UTC
There is another thread that mentions freezes. I was interested in figuring out how I can find out what the issue is.
I am on fedora 32, and I am getting video freezes when I am in a conference that makes slack totally unresponsive. It seems to happen randomly, all of a sudden the entire video conference window freezes and also the other slack windows are unresponsive. I can still talk and hear others but my webcam is frozen to others.

How can I help figure out what the error is that causes the crash? Where are the logs?

**Comment by MinallW** [comment] 2021-11-17 13:51
This also happends to me. I'm on **Fedora 35** with **Gnome 41.1** and **Wayland**.

For me, the app works perfectly, but at random times the when I open the app I and try to do something, a 'App does not respond' -wait or stop- message appears everytime.

I can use the app for a day without this problem, but if it appears at first, I have to spend all day with it, in this state I cannot copy any content, text nor Images because slack freezes again.

**Comment by gmaratos** [comment] 2021-11-17 18:43
I am only guessing, but maybe it's a video memory issue? When you start to notice problems does restarting your machine change anything?

**Comment by MinallW** [comment] 2021-11-17 18:47
I'm right now with Slack on my terminal but, the error hasn't shown so, everything is perfect. I don't reproduce videos btw. Here's some log for my slack session, no error:
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/lib/slack/slack --type=zygote
Initializing local storage instance
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
Gtk-Message: 08:54:30.763: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:54:30.763: Failed to load module "pk-gtk-module"
Gtk-Message: 08:54:30.763: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:54:30.763: Failed to load module "pk-gtk-module"
[2:1117/085430.778598:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[47:1117/085430.950853:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
LaunchProcess: failed to execvp:
xdg-settings
[2:1117/085431.034551:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1117/085431.034622:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1117/085431.034682:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1117/085431.060488:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085431.060714:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085435.083778:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085435.175664:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085435.175886:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085438.920023:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085438.920201:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085439.568563:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085439.569026:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085441.288210:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085441.288429:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085441.968564:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085441.968715:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085442.590789:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2:1117/085442.590937:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Gkr-Message: 08:55:00.995: secret service operation failed: org.freedesktop.DBus.Error.ServiceUnknown
[79:1117/095231.712905:ERROR:webrtc_video_engine.cc(3470)] Absent receive stream; ignoring clearing encoded frame sink for ssrc 0

Once the error shows itself, I should see something on the consol to help you debug.

**Comment by MinallW** [comment] 2021-11-17 23:23
Good news, the error happened after some time:
[79:1117/095231.712905:ERROR:webrtc_video_engine.cc(3470)] Absent receive stream; ignoring clearing encoded frame sink for ssrc 0

^[[5;7~[79:1117/165911.167784:ERROR:webrtc_video_engine.cc(3470)] Absent receive stream; ignoring clearing encoded frame sink for ssrc 0
[79:1117/170513.116578:ERROR:webrtc_video_engine.cc(3470)] Absent receive stream; ignoring clearing encoded frame sink for ssrc 2211325086

Don't know if having night light has something to do?... How should I fix this, perhaps am I missing a package @gmaratos ?

**Comment by evan-a-a** [comment] 2023-12-12 15:42
Closing due to age.

**Closed by evan-a-a** 2023-12-12 15:42 UTC
