### ISSUE TITLE
Flathub Install Error: Wrong size for extra data

### ISSUE THREAD

**Issue by c-nv-s** [flathub/com.slack.Slack#288] opened 2024-07-04 21:33 UTC
Flathub install failing with error message:

```
Error: Wrong size for extra data https://api.snapcraft.io/api/v1/snaps/download/JUJH91Ved74jd4ZgJCpzMBtYbPOzTlsD_153.snap
error: Failed to install com.slack.Slack: Wrong size for extra data https://api.snapcraft.io/api/v1/snaps/download/JUJH91Ved74jd4ZgJCpzMBtYbPOzTlsD_153.snap

```

for reference see: https://github.com/flatpak/flatpak/issues/5655#issuecomment-1910951252

**Comment by ZVNexus** [comment] 2024-07-19 01:58
Closing for same issue in the reference issue. Cannot reproduce.

**Closed by ZVNexus** 2024-07-19 01:58 UTC
