### ISSUE TITLE
Links don't open

### ISSUE THREAD

**Issue by tlaundal** [flathub/com.slack.Slack#106] opened 2021-01-14 10:51 UTC
Nothing happens if I left click on a link, nor if I right click and select "Open link".
This goes for both links directly in a message, to a channel or in DMs, and in embed cards from links.

Slack version: 4.12.2 64-bit dd5cf43-s@1610601554
Running on Fedora 33 with Gnome 3.38.2.
Default browser: Firefox 84.
I installed slack through the "Software" program in Fedora.

The snap version works fine, and reports the exact same slack version (including commit hash).

**Comment by vchernin** [comment] 2021-05-04 21:45
I cannot reproduce this issue on fedora 34 silverblue with firefox 88.
Slack correctly opens any links in firefox as expected.

Can you try running the slack from the command line and reporting any error/warning messages?
`flatpak run com.slack.Slack`

**Comment by evan-a-a** [comment] 2023-12-12 15:42
Closing due to age.

**Closed by evan-a-a** 2023-12-12 15:42 UTC
