### ISSUE TITLE
Missing icon and app/window not present in application switcher

### ISSUE THREAD

**Issue by krashekspres** [flathub/com.slack.Slack#37] opened 2019-05-24 10:21 UTC
On xfce4 icon is a default (fallback gtk) icon, and slack is not in the list of application switcher (alt+tab).
xfce 4.12
opensuse tumbleweed 
flatpak 1.2.4

Other flatpaks are working fine, I found this issue only on Slack.

**Comment by krashekspres** [comment] 2019-05-30 07:34
Created a script as a temp workaround, the script should be run after Slack loads.
```
#!/bin/bash
ICON=~/.local/share/flatpak/app/com.slack.Slack/current/active/export/share/icons/hicolor/512x512/apps/com.slack.Slack.png

WINDOWS=(`wmctrl -l | grep "Slack - " | cut -f1 -d' ' | xargs`)
for slack_window in ${WINDOWS[@]}; do
    # Use "xseticon", a compiled C binary, to change the icon of a running program
    ~/bin/xseticon-0.1+bzr14/xseticon -id ${slack_window} $ICON

    # Use "xprop" to set the window state, so that alt+tab works again
    xprop -f _NET_WM_WINDOW_TYPE 32a -set _NET_WM_WINDOW_TYPE _NET_WM_WINDOW_TYPE_NORMAL -id ${slack_window}
done
```

**Comment by FakeShemp** [comment] 2019-06-02 13:16
I just updated the icon. If you could try it now would be great.

**Comment by FakeShemp** [comment] 2019-07-09 13:49
Duplicate of https://github.com/flathub/com.slack.Slack/issues/9

**Closed by FakeShemp** 2019-07-09 13:49 UTC
Labels: duplicate

**Comment by KlGreph** [comment] 2020-03-31 10:29
It can help to human who will have this problem too
start your Slack app by this script

`#!/bin/bash

function changeWinIco
{
  slackWinInfo=$(xwininfo -tree -root | grep -o '^.*\s\WSlack\s\W')
  IFS=" " read -a winInfoArr <<< "$slackWinInfo"
  slackWinID=${winInfoArr[0]}

  if [ -n "$slackWinID" ]; then
    xseticon -id $slackWinID $HOME/.icons/slack.png
    exit
  fi

  sleep 2; changeWinIco
}

slack & changeWinIco
`
