### ISSUE TITLE
Random and extended freezing on Fedora 28

### ISSUE THREAD

**Issue by EspadaV8** [flathub/com.slack.Slack#24] opened 2018-08-22 23:37 UTC
I mention Fedora because the issue doesn't seem to happen on Ubuntu on my laptop, only Fedora on my Desktop. The freezes don't seem to happen as a trigger to something happening (like a message arriving or a notification) and they can persist for a long while. I've basically switched from the flatpak to just visiting the site in Chrome.

```
espadav8@localhost:~
> flatpak -v --version
Flatpak 0.99.3

espadav8@localhost:~
> flatpak info com.slack.Slack
Ref: app/com.slack.Slack/x86_64/stable
ID: com.slack.Slack
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-08-18 00:17:59 +0000
Subject: Switch to stable runtime version 18.08 (57451b64)
Commit: f1549d47f7d6eb3e7947b5e7b47ba82623c2d342237ab3905708ad80dc4e144e
Parent: efaa01777c1a7f03ce7f9c6b395ae410f19eec8098e59df2787c75eef0712768
Location: /var/lib/flatpak/app/com.slack.Slack/x86_64/stable/f1549d47f7d6eb3e7947b5e7b47ba82623c2d342237ab3905708ad80dc4e144e
Installed size: 2.8 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08
```

**Comment by EspadaV8** [comment] 2018-08-22 23:57
Running with `-d` and I noticed these errors appearing

```
(slack:2): libnotify-WARNING **: 09:54:43.455: Failed to connect to proxy

(slack:2): libnotify-WARNING **: 09:55:08.481: Failed to connect to proxy

(slack:2): libnotify-WARNING **: 09:55:18.786: Failed to connect to proxy
```

Not sure if they're related to the hanging

**Comment by TingPing** [comment] 2018-08-23 00:58
`libnotify` is a terrible library that does block so it is very likely. That error is probably a host problem not a Flatpak one if I had to guess. Maybe `flatpak run --log-session-bus com.slack.Slack` gives useful output though.

**Comment by EspadaV8** [comment] 2018-08-23 01:17
Thanks, I'll run it with that and post what it shows. If it is a host issue are you aware of anything I could do to mitigate the issue?

**Comment by EspadaV8** [comment] 2018-08-23 01:35
Now I've actually been paying attention to when it's hanging it does seem to be when a notification comes in and it makes the 'plink' sound. I'm guessing libnotify is trying to show a notification onscreen (since the sound does play). I wonder if it's something to do with KDE (since my Ubuntu install is running Gnome).

```
(slack:2): libnotify-WARNING **: 11:30:39.321: Failed to connect to proxy
C63: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
C64: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
C65: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C66: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C67: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B37: <- org.freedesktop.DBus return from C63
B38: <- org.freedesktop.DBus return from C64
B39: <- org.freedesktop.DBus return from C65
B40: <- org.freedesktop.DBus return from C66
B41: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.Spawn.ChildExited from C57
B42: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.Spawn.ChildExited from C62
B43: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.Spawn.ChildExited from C67
C68: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus

(slack:2): libnotify-WARNING **: 11:30:49.754: Failed to connect to proxy
C69: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B44: <- org.freedesktop.DBus return from C68
C70: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C71: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C72: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B45: <- org.freedesktop.DBus return from C69
B46: <- org.freedesktop.DBus return from C70
B47: <- org.freedesktop.DBus return from C71
C73: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
C74: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
C75: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C76: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C77: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B48: <- org.freedesktop.DBus return from C73
B49: <- org.freedesktop.DBus return from C74
B50: <- org.freedesktop.DBus return from C75
B51: <- org.freedesktop.DBus return from C76
C78: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
C79: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B52: <- org.freedesktop.DBus return from C78
B53: <- org.freedesktop.DBus return from C79
C80: -> all signal org.kde.StatusNotifierItem.NewIconThemePath at /org/ayatana/NotificationItem/Slack1
C81: -> all signal org.kde.StatusNotifierItem.NewIcon at /org/ayatana/NotificationItem/Slack1
B1012: <- :1.31 call org.freedesktop.DBus.Properties.GetAll at /org/ayatana/NotificationItem/Slack1
C82: -> :1.31 return from B1012
B54: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.Spawn.ChildExited from C72
B55: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.Spawn.ChildExited from C77
C83: -> all signal org.kde.StatusNotifierItem.NewIconThemePath at /org/ayatana/NotificationItem/Slack1
C84: -> all signal org.kde.StatusNotifierItem.NewIcon at /org/ayatana/NotificationItem/Slack1
B1013: <- :1.31 call org.freedesktop.DBus.Properties.GetAll at /org/ayatana/NotificationItem/Slack1
C85: -> :1.31 return from B1013
C86: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C87: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C88: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B56: <- org.freedesktop.DBus return from C86
B57: <- org.freedesktop.DBus return from C87
```

**Comment by EspadaV8** [comment] 2018-08-23 02:47
I've disabled notifications in Slack and it no longer hangs. I also don't see the libnotify messages in the log. I'll give standalone Slack a go as well and see if that has similar libnotify issues.

**Comment by EspadaV8** [comment] 2018-08-23 02:57
Testing with the RPM from the Slack website and notifications still cause a hang (although they are displayed, which doesn't happen with the flatpak). It would appear this is a Slack and/or Fedora issue.

**Comment by TingPing** [comment] 2018-08-24 18:46
Strange, hard to say whats going on without a debugger.

**Comment by MichaelAquilina** [comment] 2018-10-07 20:53
I *think* I am experiencing the same thing in OpenSUSE Tumbleweed. Will try check the logs tomorrow when I have the machine available to me.

**Comment by FakeShemp** [comment] 2019-07-09 13:53
Still an issue? Should be fixed upstream.

**Comment by supcry** [comment] 2020-04-02 21:39
I have the same problem till now (gentoo, net-im/slack-bin-4.3.2-r3::nest).
I have to disable all notifications to live with it.

To reproduce the bug just click on "Menu->File->Preferences->Notifications->"Show me an example notification.". All content of window will freeze for about of one minute.

**Comment by kaihendry** [comment] 2020-04-17 03:48
I think I have the same issue on Archlinux using the 4.4.2-1 package.

I wouldn't say it freezes, because it can render still. It's just that **all interactivity stops**. Tbh I've seen this on Chromium and VScode. Nightmare.

https://s.natalian.org/2020-04-17/slack-strace.log

**Comment by richRemer** [comment] 2020-04-27 20:05
I am experiencing this issue every time I receive a notification.

Running Ubuntu 19.10.  Stopped freezing up after disabling notifications.

**Comment by evan-a-a** [comment] 2023-12-11 15:23
Closing due to age.

**Closed by evan-a-a** 2023-12-11 15:23 UTC
