### ISSUE TITLE
Slack crashes in share screen attempt in Wayland (regression)

### ISSUE THREAD

**Issue by dmvianna** [flathub/com.slack.Slack#196] opened 2023-04-26 12:02 UTC
The latest commit aa799fc26d61a699bb3a283d0f2453aaffbe0bce causes Slack to crash when attempting to share screen. This is fixed by pinning Slack to the previous commit:

```
sudo flatpak update \                            
--commit=b95d24a8a354db07b95b065b3e57e9442c9fbaf851a49cbe6e7b1aa0afcab591 \
com.slack.Slack
```

You also need to prevent updates until this issue is fixed. 
```
flatpak mask com.slack.Slack
```

**Comment by francoisrob** [comment] 2023-04-26 12:58
Appreciate this. Been having the same issues until I switched to xorg after I was unable to share screen in a meeting.

**Comment by jcontonio** [comment] 2023-05-09 18:19
Yeah I'm seeing the same crash, even after restart with running this commit

**Comment by devurandom** [comment] 2023-05-10 15:05
For me Slack crashed on commit `72345beafe0cb9d2b32b4f602a6b5392c23a987747f43340a387827f85b552a1`. I can confirm that screen sharing works fine after `sudo flatpak update --commit=b95d24a8a354db07b95b065b3e57e9442c9fbaf851a49cbe6e7b1aa0afcab591 com.slack.Slack`.

**Comment by amine-err** [comment] 2023-05-12 10:22
Can also confirm returning to the mentioned commit fixes screen sharing

**Comment by lucaxs09** [comment] 2023-05-22 16:35
It works perfectly! Thanks for sharing.

**Comment by mpuls** [comment] 2023-05-23 09:27
As far as I understand, the commit https://github.com/flathub/com.slack.Slack/commit/aa799fc26d61a699bb3a283d0f2453aaffbe0bce just has changed the download URL from slack deb-package to the newer version `4.31.155`. Installing and using that version or even the newer version `4.32.122`directly from a download via the slack homepage also results in the here described crashes for me. Therefore, I think it is not related to the flatpak version at all but directly to problem within slack.

**Comment by francoisrob** [comment] 2023-05-23 09:52
Yeah, screensharing with slack even with the recommended commit has always
been a bit buggy. For me screen sharing on wayland on the previous versions
does not show the screens in wayland screenshare option, so I have to hover
over to choose which option depending on the active block which is
highlighted luckily. Tried to revert to the last commit, but I guess I'll
just log out and use xorg for meetings

**Comment by grandchild** [comment] 2023-05-24 10:22
> Has anyone tested #201 ?

I have a native install of slack 4.32.122, and it still crashes. :/

**Comment by igaldino** [comment] 2023-06-07 14:22
> See how "active commit" is the broken version, while "latest commit" is the version I want and upgraded to. Did anyone ever run into a situation like this? How can I convince Flatpak to make the "latest commit" the "active commit"?

It's probably masked, so you need to unmask it, downgrade and then remask it:

```
flatpak --remove mask com.slack.Slack
sudo flatpak update --commit=b95d24a8a354db07b95b065b3e57e9442c9fbaf851a49cbe6e7b1aa0afcab591 com.slack.Slack
flatpak info com.slack.Slack 
flatpak mask com.slack.Slack
```

**Comment by bhack** [comment] 2023-06-13 01:30
Have you tested https://github.com/flathub/com.slack.Slack/pull/203 ?

**Comment by afiestas** [comment] 2023-06-13 06:33
> Have you tested #203 ?

Tried #203, for me still crashes with both, XWayland and KWin-Wayland.

**Comment by proton5000** [comment] 2023-07-13 08:43
the `b95d24a8a354db07b95b065b3e57e9442c9fbaf851a49cbe6e7b1aa0afcab591`
works on Fedora, kernel: x86_64 Linux 6.3.11-200.fc38.x86_64, Wayland, GNOME 44.3, cpu: 11th Gen Intel Core i5-1135G7 @ 8x 4.2GHz, gpu: Mesa Intel(R) Xe Graphics (TGL GT2)

thanks

**Comment by friimaind** [comment] 2023-07-13 10:37
Unfortunately it also crashes on my system:

```
EndeavourOS (Arch) 2021.11.30
Slack 4.32.127
kernel x86_64 Linux 6.4.3-arch1-1
GNOME Wayland 44.3
Electron version v25.2.1
```

**Comment by infra-monkey** [comment] 2023-07-14 08:24
Hello,
It looks like it just got fixed upstream in electron
https://github.com/electron/electron/pull/38833
Need to wait for slack to include this change. If someone has already an open case with slack for that, it would be nice to notify them.

**Comment by grandchild** [comment] 2023-07-14 08:32
Would also probably need to wait for an Electron release first...

**Comment by PichlerD** [comment] 2023-07-25 09:47
Using this version it doesn't crash for me anymore, but also fails to share the screen or tabs. Ubuntu 22.04 I can now click on the button and window pops up asking me what to share without previews if i click one i can select a window or the full screen. But then it still fails

**Comment by benthejack-vuw** [comment] 2023-08-18 15:20
I can't get it not to crash at the moment so have resorted to opening slack in the browser in app mode:
brave --class=Brave --app=https://my-org.slack.com
you could do this with chrome also - everything seems to be a lot more stable this way anyway.

**Comment by yashoswalyo** [comment] 2023-09-08 14:48
Confirming that with `b95d24a8a354db07b95b065b3e57e9442c9fbaf851a49cbe6e7b1aa0afcab591` screen recording is working
```
Os: Fedora Linux 38 (Workstation Edition) x86_64
kernel: 6.4.13-200.fc38.x86_64 
Wayland
GNOME 44.4
cpu: 11th Gen Intel i7-1185G7 (8) @ 4.800GHz
gpu: Intel TigerLake-LP GT2 [Iris Xe Graphics]
```

**Comment by dchw** [comment] 2023-09-08 16:45
Slack seems to have released an update that fixes this? (4.34.115): https://slack.com/release-notes/linux. Switching to this version seems to have fixed it, while the older 4.33.90 native install had the same behavior as the Flatpak.

**Comment by borgille** [comment] 2023-09-10 16:28
> Slack seems to have released an update that fixes this? (4.34.115): https://slack.com/release-notes/linux. Switching to this version (native install) seems to have fixed it, while the older 4.33.90 native install had the same behavior as the Flatpak did.

I tried 4.34.115 via snap  on Nobara 38 and although it didn't segfault this time it just hung when executing "Run an audio, video and screensharing test" from _Preferences -> Audio & Video -> Troubleshooting_.  Falling back to `b95d24a8a354db07b95b065b3e57e9442c9fbaf851a49cbe6e7b1aa0afcab591` via Flatpak passes all tests for me.

    Os: Nobara-38-KDE-Nvidia-2023-08-29
    kernel: 6.4.10-202.fsync.fc38.x86_64
    GPU: NVIDIA RTX A3000 Laptop GPU
    NVIDIA Driver Version: 535.104.05

**Comment by toadjaune** [comment] 2023-09-28 20:27
I just upgraded my flatpak install to version `4.34.120`, and this solves the issue for me.

Well, kind of. Screensharing doesn't work yet, it sends a black screen, but it doesn't crash anymore.

Details on my setup : 
* Fedora 38
* Linux 6.4.15-200.fc38.x86_64
* sway window manager

**Comment by 1player** [comment] 2023-09-29 07:27
Then it isn't solved, since the old version mentioned in the previous comments has working screen sharing.

**Comment by toadjaune** [comment] 2023-09-29 07:46
I'm not sure it ever worked on my setup, so, I'll let others confirm if anything changed for them

**Comment by colinrgodsey** [comment] 2023-09-30 18:37
I can also confirm that `4.34.120` works while the currently published version does not (I have not tried the new version in a few weeks, may have been fixed by now... not sure)

**Comment by lufia** [comment] 2023-10-02 03:22
In my linux box, `4.34.120` don't crash on start sharing screen. But **share screen** menu listed only x11 apps, and sharing **entire desktop** shares always black screen.

**Comment by bhack** [comment] 2023-10-02 07:56
> In my linux box, `4.34.120` don't crash on start sharing screen. But **share screen** menu listed only x11 apps, and sharing **entire desktop** shares always black screen.

Yes it is well known:
https://forums.slackcommunity.com/s/question/0D53a00009BSEGACA5/when-will-slack-support-wayland-screen-sharing-does-anyone-have-workarounds-or-hacks-to-make-it-work

**Comment by turculaurentiu91** [comment] 2023-10-31 14:33
As a workaround, I am using this: https://github.com/KDE/xwaylandvideobridge

**Comment by anton-x-t** [comment] 2023-10-31 15:09
Tried `xwaylandvideobridge` but it just works between every 1 out of 10 to 1 out of 20 times so not my cup of tea.

**Comment by kohane27** [comment] 2023-11-08 07:11
> As a workaround, I am using this: https://github.com/KDE/xwaylandvideobridge A quick setup script for flatpak https://github.com/JerrySM64/Xwayland-Video-Bridge-Quick-Setup/

@turculaurentiu91 
Could you elaborate how you make it work?
I've installed xwaylandvideobridge but when I launched slack, there's no option to select any screen.
Thanks in advance!

**Comment by turculaurentiu91** [comment] 2023-11-08 09:07
> > As a workaround, I am using this: https://github.com/KDE/xwaylandvideobridge A quick setup script for flatpak https://github.com/JerrySM64/Xwayland-Video-Bridge-Quick-Setup/
> 
> @turculaurentiu91 Could you elaborate how you make it work? I've installed xwaylandvideobridge but when I launched slack, there's no option to select any screen. Thanks in advance!

After you install it, make sure it's running, it should have a system tray icon. It's an app on your computer, I have set it up to start when I boot!
![image](https://github.com/flathub/com.slack.Slack/assets/8848006/a8d9a447-1994-4292-94d2-735e8e18fa43)

Then, when you share your screen on slack, you should choose "Wayland to X11 Video Bridge"
![image](https://github.com/flathub/com.slack.Slack/assets/8848006/ddd2c200-ecd3-4e06-a7db-670013f0a141)

Then you will have wayland asking you a couple of times what screen you want to share!

However, I am experiencing crashes when I share the PhpStorm window.

**Comment by kohane27** [comment] 2023-11-08 10:19
@turculaurentiu91 

Thank you so much for getting back to me.

I'm on [Swaywm](https://swaywm.org/).

I run `xwaylandvideobridge` with `flatpak run org.kde.xwaylandvideobridge` and it becomes a floating blank screen:

xbridge.png

Regardless, I tried screen sharing and choose the white blank screen `Wayland to X11 Video Bridge`.

blank-.png

Note: first two blank screen is my dual monitors; third one is the slack app itself

Then:

```
✖ flatpak run org.kde.xwaylandvideobridge
org.kde.xwaylandvideobridge: Couldn't initialize the remote control session
```

In Slack:

> Can’t share your screen
> Check your system preferences to make sure Slack has screen recording permission, and try again.

Does it mean `xwaylandvideobridge` will only work under KDE? Thanks again!

**Comment by anton-x-t** [comment] 2023-11-13 15:08
Thank you a big bunch @xHeaven 

Tested on 2023-11-13 and and it's working on Fedora 39 `Linux fedora 6.5.11-300.fc39.x86_64` with Wayland `XDG_SESSION_TYPE=wayland` and `slack -v`: `4.35.126`.

Updated guide:
1. Remove any Slack version you have installed currently that is not from https://slack.com/downloads/linux.
2. Install the `.deb` or `.rpm` version of Slack from their website - not from Flatpak, nor Snap.
3. Run `sudo sed -i '.backup' -e 's/,"WebRTCPipeWireCapturer"/,"LebRTCPipeWireCapturer"/' /usr/lib/slack/resources/app.asar`
4. Run `sudo sed -i -e 's#Exec=/usr/bin/slack %U#Exec=/usr/bin/slack\ %U\ --enable-features=WebRTCPipeWireCapturer#' /usr/share/applications/slack.desktop`

Credits:
Guide for WebRTCPipeWireCapturer for latest Slack Version,
thank you xHeaven,
https://github.com/flathub/com.slack.Slack/issues/101#issuecomment-1807073763

**Comment by evan-a-a** [comment] 2023-12-12 16:17
Closing, upstream issue. Also duplicates #150

**Closed by evan-a-a** 2023-12-12 16:17 UTC

**Comment by anton-x-t** [comment] 2023-12-13 13:08
@evan-a-a Where is the upstream issue?

**Comment by evan-a-a** [comment] 2023-12-14 16:16
> @evan-a-a Where is the upstream issue?

There's a community moderator response over on the Slack forums. This is also linked in https://github.com/flathub/com.slack.Slack/issues/101#issuecomment-1838579367
 https://forums.slackcommunity.com/s/question/0D53a00009BSEGACA5/when-will-slack-support-wayland-screen-sharing-does-anyone-have-workarounds-or-hacks-to-make-it-work?language=en_US

**Comment by markonisic** [comment] 2024-01-24 08:54
> Thank you a big bunch @xHeaven
> 
> Tested on 2023-11-13 and and it's working on Fedora 39 `Linux fedora 6.5.11-300.fc39.x86_64` with Wayland `XDG_SESSION_TYPE=wayland` and `slack -v`: `4.35.126`.
> 
> Updated guide:
> 
>     1. Remove any Slack version you have installed currently that is not from https://slack.com/downloads/linux.
> 
>     2. Install the `.deb` or `.rpm` version of Slack from their website - not from Flatpak, nor Snap.
> 
>     3. Run `sudo sed -i -e 's/,"WebRTCPipeWireCapturer"/,"LebRTCPipeWireCapturer"/' /usr/lib/slack/resources/app.asar`
> 
>     4. Run `sudo sed -i -e 's#Exec=/usr/bin/slack %U#Exec=/usr/bin/slack\ %U\ --enable-features=WebRTCPipeWireCapturer#' /usr/share/applications/slack.desktop`
> 
> 
> Credits: Guide for WebRTCPipeWireCapturer for latest Slack Version, thank you xHeaven, [#101 (comment)](https://github.com/flathub/com.slack.Slack/issues/101#issuecomment-1807073763)

Just to confirm that this workaround also works for me. Fedora 39 workstation, Wayland, Kernel 6.6.12-200.fc39.x86_64, Gnome 45.3,  Slack 4.36.138 64-bit.

**Comment by anton-x-t** [comment] 2024-01-24 09:21
Thank you @evan-a-a for the reply!

**Comment by anton-x-t** [comment] 2024-01-24 09:21
> > @evan-a-a Where is the upstream issue?
> 
> There's a community moderator response over on the Slack forums. This is also linked in [#101 (comment)](https://github.com/flathub/com.slack.Slack/issues/101#issuecomment-1838579367) https://forums.slackcommunity.com/s/question/0D53a00009BSEGACA5/when-will-slack-support-wayland-screen-sharing-does-anyone-have-workarounds-or-hacks-to-make-it-work?language=en_US

Thank you @evan-a-a ! Sorry for the late reply!

**Comment by anton-x-t** [comment] 2024-01-24 09:36
> > Thank you a big bunch @xHeaven
> > Tested on 2023-11-13 and and it's working on Fedora 39 `Linux fedora 6.5.11-300.fc39.x86_64` with Wayland `XDG_SESSION_TYPE=wayland` and `slack -v`: `4.35.126`.
> > Updated guide:
> > ```
> > 1. Remove any Slack version you have installed currently that is not from https://slack.com/downloads/linux.
> > 
> > 2. Install the `.deb` or `.rpm` version of Slack from their website - not from Flatpak, nor Snap.
> > 
> > 3. Run `sudo sed -i -e 's/,"WebRTCPipeWireCapturer"/,"LebRTCPipeWireCapturer"/' /usr/lib/slack/resources/app.asar`
> > 
> > 4. Run `sudo sed -i -e 's#Exec=/usr/bin/slack %U#Exec=/usr/bin/slack\ %U\ --enable-features=WebRTCPipeWireCapturer#' /usr/share/applications/slack.desktop`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Credits: Guide for WebRTCPipeWireCapturer for latest Slack Version, thank you xHeaven, [#101 (comment)](https://github.com/flathub/com.slack.Slack/issues/101#issuecomment-1807073763)
> 
> Just to confirm that this workaround also works for me. Fedora 39 workstation, Wayland, Kernel 6.6.12-200.fc39.x86_64, Gnome 45.3, Slack 4.36.138 64-bit.

Nice @markonisic ! Confirmed screen sharing working for me too, Fedora 39 workstation, Wayland, Kernel 6.6.12-200.fc39.x86_64, Gnome 45.3, Slack 4.36.138 64-bit (2df428e55a64e45d5c994086577ad7d46b1eef83@1706078246).

**Comment by ZVNexus** [comment] 2024-01-24 19:04
> > Thank you a big bunch @xHeaven
> > Tested on 2023-11-13 and and it's working on Fedora 39 `Linux fedora 6.5.11-300.fc39.x86_64` with Wayland `XDG_SESSION_TYPE=wayland` and `slack -v`: `4.35.126`.
> > Updated guide:
> > ```
> > 1. Remove any Slack version you have installed currently that is not from https://slack.com/downloads/linux.
> > 
> > 2. Install the `.deb` or `.rpm` version of Slack from their website - not from Flatpak, nor Snap.
> > 
> > 3. Run `sudo sed -i -e 's/,"WebRTCPipeWireCapturer"/,"LebRTCPipeWireCapturer"/' /usr/lib/slack/resources/app.asar`
> > 
> > 4. Run `sudo sed -i -e 's#Exec=/usr/bin/slack %U#Exec=/usr/bin/slack\ %U\ --enable-features=WebRTCPipeWireCapturer#' /usr/share/applications/slack.desktop`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Credits: Guide for WebRTCPipeWireCapturer for latest Slack Version, thank you xHeaven, [#101 (comment)](https://github.com/flathub/com.slack.Slack/issues/101#issuecomment-1807073763)
> 
> Just to confirm that this workaround also works for me. Fedora 39 workstation, Wayland, Kernel 6.6.12-200.fc39.x86_64, Gnome 45.3, Slack 4.36.138 64-bit.

FYI this workaround is currently in the Flathub package, and works out of the box now.
