### ISSUE TITLE
Clicking "Sign In" button does not do anything

### ISSUE THREAD

**Issue by Noah-Huppert** [flathub/com.slack.Slack#34] opened 2019-04-04 07:45 UTC
After installing Slack from Flat Hub and running `com.slack.Slack` I am presented with a sign in screen.

On this screen there is a "Sign In" button.  

When I click this button, nothing happens.  

Clicking the "getting started" link also does not do anything.

From the release notes I think a link is supposed to open in my browser.

```
% uname -a
Linux apollo 5.0.5_1 #1 SMP PREEMPT Wed Mar 27 18:26:19 UTC 2019 x86_64 GNU/Linux
```
```
% lsb_release -a
LSB Version:	1.0
Distributor ID:	VoidLinux
Description:	Void Linux
Release:	rolling
Codename:	void
```
```
% flatpak list
Slack - Chat with your team	com.slack.Slack	3.3.8	stable	x86_64	slack-origin	system
Freedesktop.org Application Platform version 18.08 - Shared libraries provided by freedesktop.org	org.freedesktop.Platform		18.08	x86_64	flathub	system
Intel	org.freedesktop.Platform.VAAPI.Intel		18.08	x86_64	flathub	system
html5-codecs	org.freedesktop.Platform.html5-codecs		18.08	x86_64	flathub	system
```
```
% flatpak run com.slack.Slack
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
Creating Slack Application

(slack:2): libappindicator-WARNING **: 03:47:23.223: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”

(slack:2): LIBDBUSMENU-GLIB-WARNING **: 03:47:23.223: Unable to get session bus: Unknown or unsupported
transport “disabled” for address “disabled:”

(slack:2): IBUS-WARNING **: 03:47:24.443: Unable to connect to ibus: Unknown or unsupported transport “disabled” for address “disabled:”
```

**Comment by bochecha** [comment] 2019-05-02 14:58
Here, clicking either button opens a new page in Firefox, where I can sign in.

Then I got redirected back to the app and it's working fine.

**Comment by Noah-Huppert** [comment] 2019-05-05 17:48
@bochecha That's interesting, that's the expected behavior for me but it doesn't happen. 

Are there any mechanisms that you think need to be set up on a user's machine for the link click to work?  
 
For example I having a default web browser setup via xdg-settings, but maybe there is something else I need to configure. Maybe something related to dbus?

**Comment by bochecha** [comment] 2019-05-05 19:07
Do you have an implementation of the XDG desktop portals installed?

On Fedora for example, the required packages **on the host** are called `xdg-desktop-portal-gtk` and `xdg-desktop-portal-kde`. You need one of them, whichever integrates better with your host OS. (e.g the `-gtk` one if you're running GNOME, MATE, XFCE, …)

**Comment by george-angel** [comment] 2019-05-29 11:29
Same issue, I have `xdg-desktop-portal-gtk` installed.

Problem is, right-clicking on the "Sign In" gives me a single, greyed out option to "Copy", so I cannot even copy the URI to my preferred browser (which would be my preference).

**Comment by bochecha** [comment] 2019-05-29 11:42
@george-angel @Noah-Huppert what browsers do both of you have installed, and how did you install them?

**Comment by george-angel** [comment] 2019-05-29 11:52
Running standard Arch Linux installation, I have Firefox and Chromium installed via pacman (from `extra` repository) and Chrome via aur.

**Comment by bochecha** [comment] 2019-05-29 12:01
Ok, this is a wild guess at this point, but… can you try running `sudo /usr/bin/update-desktop-database`?

(my suspicion is that xdg-desktop-portal searches for apps which handle the `x-scheme-handler/https;` mime-type; Firefox declares it does in its `.desktop` file, but that's only taken into account after running `update-desktop-database` and maybe the Arch package doesn't run it upon installation? pretty far fetched :sweat_smile:)

**Comment by george-angel** [comment] 2019-05-29 12:35
Hey @bochecha - not such luck, I have ran `$ sudo update-desktop-database` - but same result in Slack app.

Thank you for taking the time to reply. Let me know if I can provide more debug information.

**Comment by FakeShemp** [comment] 2019-06-02 15:47
Do you guys have `xdg-utils` installed?

**Comment by bochecha** [comment] 2019-06-02 21:34
> Do you guys have xdg-utils installed?

It should come from the org.freedesktop.Platform runtime, which this Slack app depends on.

However, that makes me think… do you have a portal implementation installed? The package should be called something like `xdg-desktop-portal-*`. As far as I know there are two implementations: `xdg-desktop-portal-gtk` and `xdg-desktop-portal-kde`. You need to have one of them installed on your host.

**Comment by george-angel** [comment] 2019-06-03 08:10
Yes to both:

```
~ 23:28:22 $ pacman -Ss xdg-utils
extra/xdg-utils 1.1.3-3 [installed]
    Command line tools that assist applications with a variety of desktop integration tasks
extra/xdg-utils-cxx 0.git20190307-2
    Implementation of the FreeDesktop specifications to be used in C++ projects
~ 09:09:39 $ pacman -Ss xdg-desktop-portal
extra/xdg-desktop-portal 1.4.2-1 [installed]
    Desktop integration portals for sandboxed apps
extra/xdg-desktop-portal-gtk 1.4.0-1 [installed]
    A GTK+ backend for xdg-desktop-portal
extra/xdg-desktop-portal-kde 5.15.5-1 (plasma)
    A backend implementation for xdg-desktop-portal using Qt/KF5
```

**Comment by FakeShemp** [comment] 2019-06-03 18:10
Could you try the latest update and see if there's any difference?

**Comment by george-angel** [comment] 2019-06-03 21:08
```
$ flatpak list
Name                          Application ID                                 Version            Branch          Installation
Slack                         com.slack.Slack                                3.4.2              stable          system
```

same I'm afraid.

**Comment by End-S** [comment] 2019-06-11 11:20
I had this issue installing Slack via Snap, it may not be relevant to FlatPak but I will share my solution just in case:

I had no defaults application set for opening http and https URLs in my OS (Kubuntu). Once I set my browser as the default for all URLs it took about 30-40 seconds after clicking "Sign In" for slack to open in my browser and allow me to complete the process.

**Comment by Alex-CD** [comment] 2019-06-13 14:56
I'm currently having the same issue as @End-S , but the following window appears instead of the slack sign in a while after clicking the sign in button.

![image](https://user-images.githubusercontent.com/10101722/59443009-2cd16300-8df3-11e9-8801-c92849a81615.png)

Snap info:

> name:      slack
> summary:   Team communication for the 21st century.
> publisher: Slack✓
> contact:   https://get.slack.help/hc/en-us
> license:   unset
> description: [...]
> commands:
>   - slack
> snap-id:      JUJH91Ved74jd4ZgJCpzMBtYbPOzTlsD
> tracking:     stable
> refresh-date: today at 15:28 BST
> channels:
>   stable:    3.4.2 2019-05-24 (14) 155MB classic
>   candidate: ↑                           
>   beta:      ↑                           
>   edge:      3.3.1 2018-08-31  (8) 148MB classic
> installed:   3.4.2            (14) 155MB classic


Kubuntu info:
> Kubuntu 19.04
> KDE plasma version: 5.15.4
> KDE frameworks version: 5.56.0
> Qt Version: 5.12.2
> Kernel version: 5.0.0-16-generic
> OS Type: 64-bit

**Comment by aroshanineshat** [comment] 2019-06-13 16:51
Same issue here, using latest version of Slack and chromium.

**Comment by FakeShemp** [comment] 2019-07-09 13:46
I'm thinking maybe mimeapps. Are there any associations to http links and the like in `~/.local/share/applications/mimeapps.list`? Something like `x-scheme-handler/https=chromium.desktop`?

**Comment by george-angel** [comment] 2019-07-09 13:53
Mine is empty

**Comment by FakeShemp** [comment] 2019-07-09 14:07
Maybe running 
```
gvfs-mime --set x-scheme-handler/http chromium-browser.desktop
gvfs-mime --set x-scheme-handler/https chromium-browser.desktop
```
to set Chromium as the default to open http/s links will help then.

**Comment by m2by** [comment] 2019-08-29 00:39
The following fixed the issue for me.  I had Slack working on Ubuntu 14 and broke when I updated to 16.04
1. Start the Slack application
2. Click on the menu item Help -> Troubleshooting -> Clear Cache and Restart
3. When Slack restarts, clicking on the Sign In button will automatically open the appropriate web page on Firefox (I didn't try it with another browser)

**Comment by lingbo-yu** [comment] 2019-09-12 03:24
@m2by I have the same problem

**Comment by calebcase** [comment] 2019-10-02 18:28
Installing `xdg-utils` and `xdg-desktop-portal-gtk` fixed the issue for me. Thanks!

Void Linux/MATE/Firefox

**Comment by petr-nehez** [comment] 2019-10-04 21:01
Same issue here on RHEL 8 - installation of mentioned packages above did not help.

**Comment by justindmyers** [comment] 2019-10-18 16:28
Having this problem on Windows 10 - Build 18999 on a brand new install.

Once I ran as an administrator it worked fine but that shouldn't be required to simply open a web browser window.

**Comment by petr-nehez** [comment] 2019-10-18 19:45
> Same issue here on RHEL 8 - installation of mentioned packages above did not help.

FYI I fixed this my using `xdg-*` util to force reseting of http/https handler (I don't remember exactly which commands I execute). After restart it started to work and a link was opened in Firefox which is my default browser.

**Comment by oniek** [comment] 2019-10-21 08:18
I had same issue on RHEL 7.7 but I fixed it. Now I have new problems:
When I lunched Slack via terminal I got
#1 Issue:
[23414:1021/095451.642614:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
#2 Issue:
when I clicked "Sign In" slack app redrirected me on slack's web - and its all. Nothing about redirected back to the app on linux.

How fix it?
Additionall I change xdg-settings/open on firefox as default browser

**Comment by divoxx** [comment] 2019-11-13 20:17
I'm curious whether everyone else having this issue is running Wayland? I'm suspicious this is a problem with Slack running w/ XWayland

**Comment by petr-nehez** [comment] 2019-11-14 07:17
@divoxx I don't think it is Wayland related because I don't use it at all.
I guess there is something weird with Electron apps which sometimes overtake http(s) handler. It has happened to me that I wanted to open a link from other app and the handler ended up in  [MS Teams app](https://github.com/IsmaelMartinez/teams-for-linux). And then it suddenly got fixed.

**Comment by FakeShemp** [comment] 2019-11-14 21:42
Are you guys using snap versions of Chrome/Firefox?

**Comment by petr-nehez** [comment] 2019-11-15 07:50
> Are you guys using snap versions of Chrome/Firefox?

No, I have Firefox from RHEL 8 repo.

**Comment by howcouldyouforget** [comment] 2020-01-14 17:42
For me, all I had to do was define a default browser, I set Chrome to be my default and it worked no problem.  The buttons are looking for a browser to use.

**Comment by prosoitos** [comment] 2020-01-17 04:16
I had this issue when the only browsers I had were quite marginal (qutebrowser and falkon). I installed Chrome and things worked fine.

**Comment by rhapidfyre** [comment] 2020-01-24 23:10
Confirming this is an issue. Just downloaded Slack (Windows 10 64bit) for a class, as the windows app is required for my course. Clicking "Sign In" or "get started" does absolutely nothing. When redirected to the app from the Slack website (such as linking Google Calendar), it doesn't respond.

Please fix ASAP. My class requires this program.

**Comment by SteenSchutt** [comment] 2020-02-14 09:02
I'm experiencing the same problem. I'm running `dwm` on Fedora 31 Minimal, so it stands to reason that some of the things like app indicators don't exist. I also have `xdg-utils` and 
```
$ uname -a
Linux callisto.irk.empire 5.4.17-200.fc31.x86_64 #1 SMP Sat Feb 1 19:00:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/os-release
NAME=Fedora
VERSION="31 (Thirty One)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Thirty One)"
```

```
$ flatpak info com.slack.Slack

Slack - Chat with your team

          ID: com.slack.Slack
         Ref: app/com.slack.Slack/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.3.2
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 3,0 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: d424cd3b08fc3a503b10dee67fc39e42c6f1e4b642b9d78392e85f24f8776abc
      Parent: 804575fb1c1b3f8c303ad88d0934830f855b37af2e05a3d877d1029c782f3cf3
     Subject: Update to 4.3.2 (ad235114)
        Date: 2020-02-11 13:09:47 +0000
```

```
(slack:2): libappindicator-WARNING **: 09:54:03.966: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”
(slack:2): LIBDBUSMENU-GLIB-WARNING **: 09:54:03.966: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”
(electron) 'getUserAgent function' is deprecated and will be removed. Please use 'userAgent property' instead.
(electron) 'setUserAgent function' is deprecated and will be removed. Please use 'userAgent property' instead.
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
(slack:2): IBUS-WARNING **: 09:54:05.461: Unable to connect to ibus: Unknown or unsupported transport “disabled” for address “disabled:”
(electron) 'setZoomLevel function' is deprecated and will be removed. Please use 'zoomLevel property' instead.
```

https://github.com/flathub/com.slack.Slack/issues/34#issuecomment-553583484
>I'm curious whether everyone else having this issue is running Wayland? I'm suspicious this is a problem with Slack running w/ XWayland

I'm on X11, so it's probably not related to Wayland.

**Comment by d3lux1999** [comment] 2020-02-20 20:06
same here, using slack latest version and firefox

**Comment by asw-v4** [comment] 2020-02-24 16:47
Ive found a work-around, by no means does this correct the actual issue, however Slack have compensated for sign in issues with their system.


1. First, navigate to [https://slack.com/ssb/signin](https://slack.com/ssb/signin)
2. Then follow the steps as indicated on the screen
3. Once you have signed in completely, copy the code onto your clipboard.
4. Navigate back to Slack-desktop. This should then automatically sign you in, without you having to click any buttons.

AFAIK you wont need to do this again unless you sign/log out

**Comment by d3lux1999** [comment] 2020-02-24 18:03
> Ive found a work-around, by no means does this correct the actual issue, however Slack have compensated for sign in issues with their system.
> 
>     1. First, navigate to https://slack.com/ssb/signin
> 
>     2. Then follow the steps as indicated on the screen
> 
>     3. Once you have signed in completely, copy the code that is displayed onto your clipboard.
> 
>     4. Navigate back to Slack-desktop. This should then automatically sign you in, without you having to click any buttons.
> 
> 
> AFAIK you wont need to do this again unless you sign/log out

Worked! Thank you.

**Comment by dginovker** [comment] 2020-02-25 15:40
**This also happens on Windows**, which suggests it's not a flatpak thing. You should update your OP so they don't think it's Linux-only

**Comment by DelicaTessa** [comment] 2020-03-15 17:12
I had the same problem but I read that Slack is supposed to open something in Firefox and my default browser was Chrome so I adjusted that and then it worked.

**Comment by petr-nehez** [comment] 2020-03-16 13:01
For Linux on Gnome I suggest to check `text/html` association (see https://help.gnome.org/admin/system-admin-guide/stable/mime-types-application-user.html.en).

**Comment by FakeShemp** [comment] 2020-03-17 14:00
If you're using a web-browser from a Snap package, the xdg-open support seem to be quite broken. If you are using for instance Chromium from Snapcraft, this might be an issue.

**Comment by dnut** [comment] 2020-03-25 17:38
This issue is not specific to flatpaks or snaps. It is a bug in slack.

I am experiencing this exact problem. I don't use any third party package managers. I have firefox and slack both installed via pacman.

```
$ xdg-mime query default x-scheme-handler/https
firefox.desktop
$ xdg-mime query default x-scheme-handler/http
firefox.desktop
$ xdg-mime query default text/html
firefox.desktop
```

Running this command opens google in firefox:

```
$  xdg-open https://google.com
```

When I click "Sign In", I see this this log message, and nothing else happens:

```
[03/25/20, 13:26:30:151] info: Got window.open with URL: /ssb/signin 
```

Clearly, slack has chosen a fragile implementation for their sign in procedure. I do not use a desktop environment, which may be related, but slack is making a mistake if they are depending on DE-specific features.

**Comment by FakeShemp** [comment] 2020-03-25 21:35
https://app.slack.com/ssb/signin gets you to the sign-in screen. The sign in button only send you to this url, it's all it does. #56 might be an issue after that though.

**Comment by FakeShemp** [comment] 2020-03-25 22:00
@dnut 
`[03/25/20, 13:26:30:151] info: Got window.open with URL: /ssb/signin`
This seems to me that slack tries to open the sign-in link with itself and fails to send it to the browser.

**Comment by dnut** [comment] 2020-03-25 22:39
> https://app.slack.com/ssb/signin gets you to the sign-in screen. The sign in button only send you to this url, it's all it does. #56 might be an issue after that though.

Yeah I got it to work with something like this. I tried @d3lux1999's url and it didn't work at first but eventually I got it somehow.

> @dnut
> `[03/25/20, 13:26:30:151] info: Got window.open with URL: /ssb/signin`
> This seems to me that slack tries to open the sign-in link with itself and fails to send it to the browser.

I see what you mean, the protocol and domain are not included. It's strange that they would do that though when they normally require you to open it in a web browser. Maybe the message is logged before they format the full url. I wonder what everyone else's logs look like.

**Comment by FakeShemp** [comment] 2020-03-25 23:44
> I see what you mean, the protocol and domain are not included. It's strange that they would do that though when they normally require you to open it in a web browser. Maybe the message is logged before they format the full url. I wonder what everyone else's logs look like.
It works on my system and it logs nothing at all. Just that the window lost focus when the browser opened.

**Comment by GTime** [comment] 2020-04-13 19:52
I had the same issue after updating but was able to sign in.

I signed in using the browser. On signed in, I opened my workspace menu and selected "Open the Slack App" and that started Slack on my desktop.

**Comment by chdeliens** [comment] 2020-04-22 06:46
> I had the same issue after updating but was able to sign in.
> 
> I signed in using the browser. On signed in, I opened my workspace menu and selected "Open the Slack App" and that started Slack on my desktop.

Manjaro 19 with KDE here, had the same issue, doing as @GTime suggested did the trick (sign into the webapp first), thanks!!!

**Comment by xwuupb** [comment] 2020-05-07 07:15
I also have the same problem by using slack + firefox (ubuntu 18.04). But this problem can be solved easily by two steps:
1. make sure `xdg-utils` has been installed on your system. If not, then install it.
2. set the default web browser to others, e.g. google-chrome.desktop, and make a try.
xdg-settings set default-web-browser google-chrome.desktop
The above two steps solved my problem.

**Comment by FakeShemp** [comment] 2020-05-09 21:18
What does `xdg-settings get default-url-scheme-handler slack` and `xdg-settings get default-url-scheme-handler https` get you for values?

These need to be set to `com.slack.Slack.desktop` and your web browser respectively.

**Comment by fake-name** [comment] 2020-05-31 07:10
Why on earth does the signin process even *use* an external browser? That's completely ridiculous. 

Slack itself is a blasted electron application which means it's basically a complete chromium instance already, there's zero good reason to have any dependency on an external browser unless they're doing creepy cross-browser user tracking.

**Comment by FakeShemp** [comment] 2020-05-31 07:26
@fake-name 
Because Google doesn't allow oauth on embedded browsers since 2017.

**Comment by fake-name** [comment] 2020-05-31 07:32
Well, then have a sign in button and a oauth button.

**Comment by ADawesomeguy** [comment] 2020-09-09 01:21
I am using Arch Linux with KDE Plasma, and I had the same issue. What fixed it for me was installing xdg-desktop-portal (not the kde one). Hope this helps!

This also fixed other URLs not working in Slack.

**Comment by jaspreetsinghrawel** [comment] 2020-11-23 13:03
I followed below steps to install slack on my uBuntu 16.04 and it resolved my issue (default browser set to chrome in the below commands)

```
# Download and install the slack package

- RUN wget https://downloads.slack-edge.com/linux_releases/slack-desktop-4.0.2-amd64.deb
- RUN apt install -y ./slack-desktop-*.deb


# Enable Slack to sign-in via the browser (setting chrome to be the default slack browser)

- RUN apt install -y xdg-utils
- RUN xdg-settings set default-web-browser chromium-browser.desktop
- RUN apt install -y xdg-desktop-portal
```

**Comment by FakeShemp** [comment] 2020-11-23 13:16
Installing the deb package will not fix any flatpak issues.

Anyway, slack now allows copying a token and pasting it to the app without having xdg-utils so I'm closing this issue.

**Closed by FakeShemp** 2020-11-23 13:16 UTC
Labels: bug, help wanted

**Comment by ddombrowsky** [comment] 2021-03-22 16:34
> Installing the deb package will not fix any flatpak issues.
> 
> Anyway, slack now allows copying a token and pasting it to the app without having xdg-utils so I'm closing this issue.

Are there any instructions on this?

**Comment by ddombrowsky** [comment] 2021-03-22 17:18
> 3. Once you have signed in completely, copy the code that is displayed onto your clipboard.

Also, this never happens for me.  It attempts `xdg-open` which just opens another chome window.  No `slack://` code is available to copy.

**Comment by ddombrowsky** [comment] 2021-03-22 17:34
figured out a work-around:
1. After logging in using `https://app.slack.com/ssb/signin`, the "redirecting..." window should open.  This will pop-up the `xdg-open` screen that will do nothing.
2. Hit `cancel` to ignore the `xdg-open` useless call.
3. Open dev tools and look at the console.

For me, there was a display, something like:
```
Launched external handler for 'slack://ABCD/efg'
```

Copy the `slack://` URI to the clipboard and then switch back to the desktop app.  It _should_ detect the url in the clipboard and sign you in to your new workspace.

That was an ordeal.

**Comment by ddombrowsky** [comment] 2021-12-02 18:17
Just one more note for the archives, and I'll shut up.

I think perhaps the root cause is the fact that the scheme handler isn't installed into the system, which means `xdg-open` doesn't know about it and thus slack won't be launched.

Copying it into the system seems to fix this (the example is for snap, but flathub has the same idea):

```
$ sudo cp /snap/slack/48/usr/share/applications/slack.desktop /usr/share/applications/
$ xdg-mime query default x-scheme-handler/slack
slack.desktop
```

You will probably have to hand-edit `/usr/share/applications/slack.desktop` to point to the correct slack binary.

**Comment by Saijin-Naib** [comment] 2022-04-27 04:21
@ddombrowsky I can't thank you enough for that fix by capturing the slack:// URI.

Also, shouldn't the scheme handler be installed properly by the flatpak?

**Comment by taekahn** [comment] 2023-03-07 14:44
2023, this is still an issue.
you are a life-saver @ddombrowsky
